// examples/my-vue-app/src/App.vue
<script setup lang="ts">
import HelloWorld from './components/HelloWorld.tsx'
</script>

<template>
  <div>
    <div style="width: 100%; height: 50px; background-color: red"></div>
    <div style='width: 100%;
    height: 100px; 
    background-color: yellow'></div>
    <div :style="{
      width: '375px',


      fontSize: '32px',


      
      height: '100px',
      backgroundColor: 'blue'
    }">

    </div>
  </div>
  <HelloWorld msg="tsx" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// examples/my-react-app/src/App.tsx
import './App.css'

function App() {
  return (
    <>
      <div 
        style={{
          height: '100px',
          width: '100px',
          backgroundColor: 'blue',
          paddingBottom: '30px',
        }}
        ref={(el) => {
          if (el) {
            el.style.setProperty('height', '100px', 'important');
            el.style.setProperty('width', '100px', 'important');
            el.style.setProperty('background-color', 'red');
            el.style.setProperty('padding-bottom', '30px', 'important');
          }
        }}>A</div>
    </>
  )
}

export default App
